# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0017_default_owner_on_delete_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Queue', verbose_name='Queue')),
            ],
        ),
    ]
