# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_queue_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queue_members',
            new_name='QueueMembers',
        ),
    ]
