# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_auto_20180722_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(blank=1, choices=[(1, '1. Request'), (2, '2. Incident'), (3, '3. Change')], default=1, help_text='Ticket Type is default to Request Please changed it as your requirements', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='queuemembers',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
    ]
