# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_auto_20180725_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(blank=1, choices=[(1, 'Request'), (2, 'Incident'), (3, 'Change')], default=1, help_text='Ticket Type is default to Request Please changed it as your requirements', verbose_name='Type'),
        ),
    ]
