# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 08:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0021_auto_20180725_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='The content of the customers query.', null=True, verbose_name='Description'),
        ),
    ]
