# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 08:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0022_auto_20180725_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='The content of the customers query.', null=True, verbose_name='Description'),
        ),
    ]
