# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 10:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0023_auto_20180725_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolution',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='The resolution provided to the customer by our staff.', null=True, verbose_name='Resolution'),
        ),
    ]
